altsem/gitu

- .github/workflows/cachix.yml
This adds a binary cache so that Nix users don't have to build gitu on their machine.
For this to work, the repo owner needs to register their project on Cachix and add the secret token to the GitHub repo. Instructions can be found from the official tutorial [here](https://nix.dev/tutorials/nixos/continuous-integration-github-actions):
> ### 1. Creating your first binary cache
> 
> It's recommended to have different binary caches per team, depending who will have write/read access to it.
> 
> Fill out the form on the [create binary cache](https://app.cachix.org/cache) page.
> 
> On your freshly created binary cache, follow the **Push binaries** tab instructions.
> 
> ### 2. Setting up secrets
> 
> On your GitHub repository or organization (for use across all repositories):
> 
> 1. Click …
> ci: add cachix workflow

- src/git/diff.rs
- src/git/mod.rs
- src/items.rs
- src/screen/show.rs
- src/screen/status.rs
'Hunk' now stores formatted 'Text'.
There was an issue where what was shown and translated into lines on the screen was the result of a
second diff between Hunks done by the 'similar' lib.
Now instead, 'similar' diffs entire files,
which makes it easier to correlate about what is
shown on screen, and what is being included in
a patch.
Moreover, this will make it easier to
apply code syntax-highlighting within diffs.
> refactor: better diffing

- src/config.rs
- src/default_config.toml
- src/state.rs
- tests/mod.rs
- tests/snapshots/r#mod__quit_prompt.snap
Implements a prompt if the user initiates a quit from the base screen.
```
? Really quit? (y or n) ›
```
> feat: add quit confirmation

- README.md
I removed the `gitu.inputs.nixpkgs.follows`, because overriding `nixpkgs` will invalidate the binary cache (the build derivation hash will change).
> doc: document nix binary cache

- src/lib.rs
- src/ops/checkout.rs
- src/ops/log.rs
- src/ops/mod.rs
- src/ops/stash.rs
- src/state.rs
- src/tests/snapshots/gitu__tests__discard__discard_branch_no.snap
- src/tests/snapshots/gitu__tests__log__log_other_invalid.snap
- src/ui.rs
- Combine 'CmdLogEntry' and 'ErrorBuffer'
- Ability to show multiple errors for multiple successive failed commands
- Break execution if 'run_cmd' or 'run_cmd_interactive' don't return 0
> fix: improve error-handling of external commands

- src/ops/stash.rs
- src/tests/mod.rs
- src/tests/snapshots/gitu__tests__stash__stash_working_tree_when_everything_is_staged.snap
- src/tests/snapshots/gitu__tests__stash__stash_working_tree_when_nothing_is_staged.snap
Stash working tree is running 3 commands so there is some edge cases which we should take into account:
1. If everything is staged don't do anything
2. If nothing is staged don't try to save index in the stash and then later pop it (either errors or pops non-related stashes)
Addresses: https://github.com/altsem/gitu/pull/100#issuecomment-2025832482
> fix: stash working tree should work when everything/nothing is staged

- src/state.rs
fix: https://github.com/altsem/gitu/issues/113
I still trying to figure out how to do not left garbage in the stash without crutches... Any ideas are welcome!
refs: https://github.com/altsem/gitu/pull/103#issuecomment-2027478578, https://github.com/altsem/gitu/pull/73#discussion_r1527529800, https://github.com/magit/magit/blob/a334412159984dcdcff3dbb56c7c1e77197cc36c/lisp/magit-stash.el#L150, https://github.com/magit/magit/blob/a334412159984dcdcff3dbb56c7c1e77197cc36c/lisp/magit-stash.el#L386
> fix: redraw screen even if command failed

- src/ops/rebase.rs
- src/tests/snapshots/gitu__tests__rebase__rebase_menu.snap
Fixes a typo found in the description of an argument on the `rebase` menu.
> fix: typo in descriptions on menu

- src/items.rs
This prevents the prefeched remotes generated by `git maintenance` from polluting the git log.
The most obvious solution seems to have worked here, and this closes #138 !
Let me know if there are other bits like changelog, etc that you'd like me to sort out!
> fix(log): ignore `prefetch/remotes/` refs

- src/git/mod.rs
- src/screen/status.rs
- src/tests/mod.rs
- src/tests/snapshots/gitu__tests__revert_conflict.snap
**Leaving this here in case anyone wants to pick it up!**
In CLI git, it typically shows this:
```
On branch main
Your branch is ahead of 'origin/main' by 2 commits.
(use "git push" to publish your local commits)
You are currently reverting commit 57409cb.
(fix conflicts and run "git revert --continue")
(use "git revert --skip" to skip this patch)
(use "git revert --abort" to cancel the revert operation)
Unmerged paths:
(use "git restore --staged <file>..." to unstage)
(use "git add/rm <file>..." as appropriate to mark resolution)
deleted by them: new-file
no changes added to commit (use "git add" and/or "git commit -a")
```
No need to show all of this, but an indicator that we are in the "reverting state" would be useful, so that the user can revert --continue, revert --abort etc. …
> wip: show revert status

- src/git/diff.rs
- src/tests/mod.rs
- src/tests/snapshots/gitu__tests__crlf_diff.snap
Before all CRLF would already be converted to LF after the diff was made (due to line 85 / how Ratatui's Text works).
Now this happens before the diff is made.
resolves: #162
I might've overlooked something, but I think this would work.
@bshashank, @rzikm
> fix: bad diffs when git's `autocrlf` was enabled

- Cargo.lock
- Cargo.toml
- src/tests/mod.rs
Runnin `cargo t` used to leave the terminal in a bad state: no mouse input is interpreted right, scrolling is gone, etc.
> test(all): restore terminal state when finished.

- src/ops/commit.rs
- src/tests/snapshots/gitu__tests__commit__commit_instant_fixup.snap
- src/tests/snapshots/gitu__tests__commit__commit_instant_fixup_stashes_changes_and_keeps_empty.snap
@stackmystack FYI. It seems that when rebasing, skipping `--interactive` when doing `--autosquash` breaks in some versions of Git.
I'm reverting it back to use `GIT_SEQUENCE_EDITOR`!
> fix: instant fixup commit would not work with some versions of Git

- README.md
- src/ops/show.rs
I changed the order of priorities for the lookup of environment variables determining the editor to use for opening files or hunks from the main menu.
It was `GIT_EDITOR`, `VISUAL`, `EDITOR` and I changed it to `VISUAL`, `EDITOR`, `GIT_EDITOR`.
The rationale for this is that one might want to use a different editor for editing e. g. commit messages (which is set by `GIT_EDITOR`) than for opening/editing the changed code, which is what these environment variables are checked for. To allow this any one of `VISUAL` or `EDITOR` should take precedence.
This resolves #246 .
This is my first ever git contribution to another project, I am very sorry if I made any grave mistakes or oversights.
> change priority order of editor envvar lookup

- src/ops/show.rs
This PR adds support for the `nvr` command, allowing users to jump directly to a specific line number using the `+[num]` option.
https://github.com/mhinz/neovim-remote
> Add support for `nvr` command with line number navigation

- flake.lock
- flake.nix
Nix build fails because nix environment contains cargo ver. 1.79.0 which is incompatible with some of the crates gitu is using. This change updates nix flake inputs, which brings in newer cargo compatible with all crates
> Fix nix build

- src/ops/show.rs
This allows users to set a custom editor used for 'show' (e.g. pressing RET on a file in the status buffer).
Please let me know if you would prefer a PR that adds this to the config file.
> show: Add `GITU_SHOW_EDITOR` env-var

- src/git/remote.rs
- src/tests/remote.rs
In the case where `get_push_remote` would have returned `Ok(None)` now first try `get_default_push_remote` which will consult the `remote.pushDefault` git config option, before either returning the fallback push remote, or no result.
Fixes #346
> feat: Fall back to remote.pushDefault when branch pushRemote is not set

- benches/show.rs
- src/config.rs
- src/error.rs
- src/lib.rs
- src/ops/checkout.rs
- src/ops/discard.rs
- src/ops/editor.rs
- src/ops/fetch.rs
- src/ops/log.rs
- src/ops/mod.rs
- src/ops/pull.rs
- src/ops/push.rs
- src/ops/rebase.rs
- src/ops/reset.rs
- src/ops/revert.rs
- src/ops/stash.rs
- src/prompt.rs
- src/state.rs
- src/term.rs
- src/tests/commit.rs
- src/tests/editor.rs
- src/tests/helpers/ui.rs
- src/tests/mod.rs
- src/tests/snapshots/gitu__tests__discard__discard_branch_no.snap
- src/tests/snapshots/gitu__tests__pull__pull_setup_push_remote.snap
- src/tests/snapshots/gitu__tests__pull__pull_setup_upstream.snap
- src/tests/snapshots/gitu__tests__push__push_setup_push_remote.snap
- src/tests/snapshots/gitu__tests__push__push_setup_upstream.snap
aims to enable: https://github.com/altsem/gitu/pull/350, and simplify the already existing use-cases.
TODO:
- Tests aren't passing
- Make it prettier? There's a bit much shared logic between the update/prompt fns
> refactor: add new state.prompt() function and simplify event handling

- Cargo.lock
- Cargo.toml
- src/error.rs
- src/file_watcher.rs
`FileWatcher` will build a gitignore ruleset from all `.gitignore` files in the repo and any global `.gitignore`, and use this to ignore file change events. This prevents a lot of `FileUpdate` events being generated when ignored items like build folders change, which may have been contributing to freezes.
If a change is detected involving a `.gitignore` file, the ruleset is rebuilt.
Changes are also now no longer watched from a thread, which caused problems with some watcher implementations such as `Fsevents` on macOS.
Fixes #359
Fixes #358
> feat: FileWatcher now ignores changes from patterns in .gitignore

- src/default_config.toml
- src/error.rs
- src/git/mod.rs
- src/git/remote.rs
- src/menu.rs
- src/ops/branch.rs
- src/ops/mod.rs
- src/tests/branch.rs
- src/tests/mod.rs
- src/tests/snapshots/gitu__tests__branch__branch_menu.snap
- src/tests/snapshots/gitu__tests__branch__checkout_new_branch.snap
- src/tests/snapshots/gitu__tests__branch__delete_branch_empty.snap
- src/tests/snapshots/gitu__tests__branch__delete_branch_forcefully.snap
- src/tests/snapshots/gitu__tests__branch__delete_branch_input.snap
- src/tests/snapshots/gitu__tests__branch__delete_branch_selected.snap
- src/tests/snapshots/gitu__tests__branch__delete_unmerged_branch.snap
- src/tests/snapshots/gitu__tests__branch__switch_branch_input.snap
- src/tests/snapshots/gitu__tests__branch__switch_branch_selected.snap
This PR adds support for deleting branches from the branch menu. If a branch hasn't been merged into upstream or HEAD, the operation must be confirmed (similar to how to `git branch -d ...` works).
> feat: add delete option to branch menu

- src/state.rs
- src/tests/branch.rs
- src/tests/editor.rs
- src/tests/snapshots/gitu__tests__editor__exit_from_prompt_exits_menu.snap
Now a failed prompt will always close the menu, as well as removing the "hidden" state of it.
And a successful prompt will always unhide the menu.
closes: 368
> fix(prompt): freeze when a command would fail after a prompt occurred

- CHANGELOG.md
- README.md
- src/ops/log.rs
Found via `typos --hidden --format brief`
> docs: fix typos

- src/config.rs
- src/default_config.toml
- src/ops/discard.rs
- src/tests/discard.rs
- src/tests/snapshots/gitu__tests__discard__discard_unstaged_line.snap
Adds discarding unstaged changes line by line.
By default you'd have to confirm each line that you unstage separately when unstaging several lines at once. As that might get a little tedious, I've added a config option `confirm_discard` that lets you choose the granularity of when to ask for confirmation:
```toml
confirm_discard = "line"  # asks on files/hunks/lines
confirm_discard = "hunk"  # asks on files/hunks
confirm_discard = "file"  # asks on files
confirm_discard = "never" # never asks, scary
```
The default is `"line"`, so you are asked to confirm no matter what you discard, which is backwards-compatible and probably the best for new users.
Curious what you think!
> feat: discard line by line (+ configure when to confirm discard)

- src/git/diff.rs
- src/ops/show.rs
The file line number that was sent to $EDITOR was relative to the start of the diff text. We now use the parsed hunk header `new_line_start`, plus an offset to get to the first edited line in the hunk.
This behavior isn't always correct of course, but it's at least better for the common case of viewing a hunk in the diff of the working tree. When viewing a diff of an older commit, the hunk new_line_start doesn't necessarily refer to the correct line in the current code (and the relevant code might no longer exist). In this case, magit will open a buffer (revived from git) which reflects the code at the time of the commit. If you press enter while on a single changed line in the hunk, magit will show you the pre-edit or post-edit version of the code, depending on whether you're on a `-` or …
> fix: opening hunk in EDITOR used wrong line number

- src/config.rs
- src/error.rs
- src/git/diff.rs
- src/items.rs
- src/ops/discard.rs
- src/ops/stage.rs
- src/ops/unstage.rs
- src/screen/mod.rs
- src/screen/show.rs
- src/screen/show_refs.rs
- src/screen/status.rs
- src/term.rs
To keep item.id as a full-blown string with an exact copy of e.g. a hunk
was a total hack. This removes it and actually hashes content instead.
This is for now used to keep track of collapsed sections between updates.
> perf: more efficiently keep track of changes between updates

- src/app.rs
- src/prompt.rs
supersedes: https://github.com/altsem/gitu/pull/394
> fix: Shift modifier & uppercase key events would not work in certain terminals

- src/ops/show.rs
With the released version, _all_ gitu commands for showing, editing etc. using the `EDITOR` env var and others will fail because we try to launch the subprocess command directly.
On Windows, this doesn't work; Commands need to be prepended with `cmd /C` to be executed in sub-shells.
> Fix a process bug when running show commands on Windows

- src/config.rs
- src/default_config.toml
- src/screen/status.rs
- src/tests/mod.rs
- src/tests/snapshots/gitu__tests__recent_commits_with_limit.snap
- src/tests/snapshots/gitu__tests__stash_list_with_limit.snap
The `general.recent_commits_limit` and `general.stash_list_limit` options can be used to configure each of these limits. They both default to 10.
Magit has `magit-log-section-commit-count` for the recent commits. However, I'm not sure Magit lets you configure the stash limit (directly), there doesn't seem to be an option and I have myself run into this annoyance when one has lots of stashes. 🫢
> feat: Allow configuring recent commits and stash list limits

- src/git/mod.rs
- src/item_data.rs
- src/items.rs
- src/ops/show.rs
- src/screen/mod.rs
- src/screen/show_stash.rs
- src/tests/mod.rs
- src/tests/snapshots/gitu__tests__show_stash.snap
Currently, the stash detail screen shows "unmerged" for all the files in the stash, which also means there is also no diff being shown for the stash.
It seems like the reason for "unmerged" is that the current implementation does `git show <stash_commit>` which ends up with `diff --cc` output, which the diff parser interprets as conflicts.
What I've changed here is to have a separate `show_stash` screen and to store the stash ref instead of the commit on the `ItemData::Stash` struct. The new screen runs `git stash show -p <stash_ref>` instead, which produces a diff that the diff parser is happier about.
I thought it was better to add something explicitly for showing stashes, rather than to try have a way to conditionally modify the diff parser, since it separates the concerns better at …
> feat: Show diff on the stash detail screen

- src/app.rs
- src/config.rs
- src/default_config.toml
- src/lib.rs
- src/ops/editor.rs
- src/ops/mod.rs
- src/screen/mod.rs
- src/term.rs
- src/tests/mod.rs
- src/tests/snapshots/gitu__tests__mouse_select_item.snap
- src/tests/snapshots/gitu__tests__mouse_show_item.snap
- src/tests/snapshots/gitu__tests__mouse_toggle_selected_item.snap
- src/tests/snapshots/gitu__tests__mouse_wheel_scroll_down.snap
- src/tests/snapshots/gitu__tests__mouse_wheel_scroll_up.snap
Magit has mouse support via emacs builtin mouse support, one particularly useful aspect of this is being able to jump around instantly instead of needing to navigate in a fashion like "next line, next line, … next line", such as when staging individual lines or moving to a particular commit/stash.
After using the mouse for a bit, I felt like perhaps there could be a few simple actions:
- Left clicking an item will move the cursor there
- Left clicking the item already at the cursor will toggle it if it's a section, or show it if not
- Right clicking an item will move the cursor there and immediately show it
- Scrolling the mouse wheel (or trackpad) scrolls the view up/down without moving the cursor position
I tried to use as much of what infrastructure was already there to support …
> feat: Simple mouse interactions

- src/ops/show.rs
`micro` is a popular modern successor to `nano`
and uses the same `+line` syntax as `nano` and `vim`.
> Support file line positions for the micro editor

- src/app.rs
- src/screen/mod.rs
- src/screen/status.rs
- src/tests/helpers/ui.rs
- src/tests/mod.rs
- src/tests/snapshots/gitu__tests__mouse_select_hunk_line.snap
- src/tests/snapshots/gitu__tests__mouse_select_ignore_empty_lines.snap
- src/tests/snapshots/gitu__tests__mouse_select_ignore_empty_region.snap
- src/tests/snapshots/gitu__tests__mouse_show_ignore_empty_lines.snap
- src/tests/snapshots/gitu__tests__mouse_show_ignore_empty_region.snap
When pressing a mouse button on empty lines, or in the empty region at the bottom of the screen, the effect is the same as having clicked on the currently selected line. This is a bit of a jarring experience because it will often perform an unexpected action relative to where the mouse cursor actually is.
This PR changes mouse click events on invalid lines to be ignored, where invalid screens lines are:
- Lines that are unselectable
- Empty lines
- Lines beyond the bounds of the screen
I added tests for selecting hunk lines and other things that I found were missing test coverage.
> fix: Ignore mouse clicks in empty regions

- flake.lock
- flake.nix
Currently, the nix builds are broken for two reasons:
1. Old version of the rust toolchain in an old version of fenix
2. Source filtering filtered out `.pest` sources when building
This change fixes both of those issues so that gitu is buildable with nix again
> Fix nix builds with newer rust and source filters
